TawredatProject/Models/SalesInvoice.cs
using System;
using System.Collections.Generic;

namespace TawredatProject.Models
{
    public class SalesInvoice
    {
        public Guid? SalesInvoiceId { get; set; }
        public string DelivryDate { get; set; }
        public string Id { get; set; }
        public string Name { get; set; }
        public Guid? DeliveryManId { get; set; }
        public string? DeliveryManName { get; set; }
        public Guid? SupplierId { get; set; }
        public string SupplierName { get; set; }
        public int PaymnetMethodId { get; set; }
        public string PaymnetMethodName { get; set; }
        public string TotalInvoiceValue { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryStatus { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string Notes { get; set; }
        public int? CurrentState { get; set; }
        public string Promocode { get; set; }
        public  List <string>item { get; set; }
        public Guid DeliveryAddressID { get; set; }
        //  public virtual ICollection<SalesInvProMV> SalesInvProMVs { get; set; }
        // public List<string> SalesInvProMVs { get; set; }
    }
   

}

TawredatProject/Areas/Admin/Controllers/SalesInvoiceController.cs
using BL;
using Domains;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System;
using TawredatProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace TawredatProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SalesInvoiceController : Controller
    {
        SalesInvoiceService salesInvoiceService;
        SalesInvoiceProductService salesInvoiceProductService;

        TawredatDbContext ctx;
        public SalesInvoiceController(SalesInvoiceService SalesInvoiceService, TawredatDbContext context, SalesInvoiceProductService SalesInvoiceProductService)
        {
            salesInvoiceProductService = SalesInvoiceProductService;

            salesInvoiceService = SalesInvoiceService;
            ctx = context;

        }
        [Authorize(Roles = "Admin,فاتورة البيع")]
        public IActionResult Index()
        {

            HomePageModel model = new HomePageModel();
            model.lstSalesInvoices = salesInvoiceService.getAll();

            return View(model);


        }
        [Authorize(Roles = "Admin,فاتورة البيع")]
        public IActionResult Adddelievery()
        {

            HomePageModel model = new HomePageModel();
            model.lstSalesInvoices = salesInvoiceService.getAll();

            return View(model);


        }

        //    [HttpGet]
        //    public IActionResult GetInvoiceDetails(int id)
        //    {
        //        var invoice = dbContext.Invoices.FirstOrDefault(i => i.Id == id); // Replace "Invoices" with your actual DbSet name

        //        if (invoice == null)
        //        {
        //            return NotFound();
        //        }

        //        return PartialView("_InvoiceDetails", invoice);
        //    }
        //}



        [HttpGet("Details/{id}")]
        [Authorize(Roles = "Admin,فاتورة البيع")]
        public IActionResult Details(Guid id)
        {
           // SalesInvoiceId = new Guid("af6565d7-f4ae-44ad-a87a-00edfd06ad89");

            List<TbSalesInvoiceProduct> invoiceProducts = salesInvoiceProductService.getAll().Where(x => x.SalesInvoiceId == id).ToList();
            List<SalesInv> sales=new List<SalesInv>();
            foreach (var invoice in invoiceProducts)
            {
                SalesInv salesIn = new SalesInv()
                {
                    SalesInvoiceId=invoice.SalesInvoiceId,
                    SupplierName=invoice.SupplierName,
                    ProductName=invoice.ProductName,
                    ProductPrice=invoice.ProductPrice,
                    ProductQty=invoice.ProductQty,
                    ProductCategoryName=invoice.ProductCategoryName,
                    TotalProductValue=invoice.TotalProductValue,
                    CreatedDate=invoice.CreatedDate
                };
                sales.Add(salesIn);

            }
          
            return View(sales);


        }

        //[HttpPost]
        //public IActionResult Details()
        //{
          
        //    HomePageModel model = new HomePageModel();
        //    model.lstSalesInvoiceProducts = salesInvoiceProductService.getAll();

        //    return View(model);


        //}




        [HttpPost]
        public async Task<IActionResult> Save(TbSalesInvoice ITEM, int id, List<IFormFile> files)
        {
            if (ITEM.SalesInvoiceId == null)
            {


                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.ab = ImageName;
                    //    }
                    //}





                    var result = salesInvoiceService.Add(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "Sales Invoice Profile successfully Created.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in Sales Invoice Profile  Creating.";
                    }


                }


            }
            else
            {
                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.MainConsultingImage = ImageName;
                    //    }
                    //}






                    var result = salesInvoiceService.Edit(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "Sales Invoice Profile successfully Updated.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in Sales Invoice Profile  Updating.";
                    }

                }
            }




            HomePageModel model = new HomePageModel();
            model.lstSalesInvoices = salesInvoiceService.getAll();
            return View("Index", model);
        }




        [Authorize(Roles = "Admin,حذف فاتورة البيع")]
        public IActionResult Delete(Guid id)
        {

            TbSalesInvoice oldItem = ctx.TbSalesInvoices.Where(a => a.SalesInvoiceId == id).FirstOrDefault();



            var result = salesInvoiceService.Delete(oldItem);
            if (result == true)
            {
                TempData[SD.Success] = "Sales Invoice Profile successfully Removed.";
            }
            else
            {
                TempData[SD.Error] = "Error in Sales Invoice Profile  Removing.";
            }

            HomePageModel model = new HomePageModel();
            model.lstSalesInvoices = salesInvoiceService.getAll();
            return View("Index", model);



        }



        [Authorize(Roles = "Admin, اضافة او تعديل فاتورة البيع")]
        public IActionResult Form(Guid? id)
        {
            TbSalesInvoice oldItem = ctx.TbSalesInvoices.Where(a => a.SalesInvoiceId == id).FirstOrDefault();
            oldItem = ctx.TbSalesInvoices.Where(a => a.SalesInvoiceId == id).FirstOrDefault();

            return View(oldItem);
        }
    }
}

TawredatProject/Areas/Admin/Views/SalesInvoice/Adddelievery.cshtml
@model TawredatProject.Models.HomePageModel
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>ربط الفواتير برجال التوصيل </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">ربط الفواتير برجال التوصيل  </a></li>
                    <li class="breadcrumb-item active">ربط الفواتير برجال التوصيل  </li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">


            <div class="card">
                <div class="card-header">
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped ">
                        <thead>
                            <tr>

                                <th> تاريخ الفاتورة </th>
                                <th>اسم المشتري </th>



                                <th>اسم طريقة الدفع     </th>
                                <th>اجمالي قيمة الفاتورة       </th>
                                <th>مكان  التسليم     </th>




                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lstSalesInvoices)
                            {

                                <tr>
                                    <td>
                                        @item.CreatedDate
                                    </td>

                                    <td>
                                        @item.SupplierName
                                    </td>

                                    <td>
                                        @item.PaymnetMethodName
                                    </td>
                                    <td>
                                        @item.TotalInvoiceAfter
                                    </td>
                                    <td>
                                        @item.DeliveryAddress
                                    </td>

                                    <td>
                                        @*                                        <a asp-controller="Landing" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-light x-Landing  px-8">Update</a>
                                    *@
                                        <a asp-controller="SalesInvoice" asp-action="Adddelievery" asp-route-id="@item.SalesInvoiceId" class="btn btn-light x-Landing  px-8">Details</a>
                                    </td>

                                </tr>

                            }


                        </tbody>

                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
@section DataTableJS{

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>


    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}

TawredatProject/Areas/Admin/Views/SalesInvoice/Details.cshtml
@model IEnumerable<SalesInv>
@{
    ViewData["Title"] = "عرض تفاصيل الفاتورة";
}
@section DataTableStyles{

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>عرض تفاصيل الفاتورة  </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">تفاصيل الفواتير   </a></li>
                    <li class="breadcrumb-item active">عرض تفاصيل الفواتير   </li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
                <!-- /.card-header -->
                <div class="card-body">
                    <form asp-controller="SalesInvoice" asp-action="Details">
                        <div class="row">
                            <div class="col-xl-11">
                                <input type="text" placeholder="Search By Name" name="MyName" class="form-control" />
                            </div>
                            <div class="col-xl-1">
                                <input type="submit" value="Search" class="btn btn-primary" />
                            </div>
                        </div>
                    </form>
                    <br />
                    <table id="MostSearchedProductsTable" class="table table-hover table-bordered table-striped text-center font-weight-bold">

                        <thead class="thead-dark">
                            <tr>
                                <th> رقم الفاتورة </th>

                             
                              

                                <th>اسم التاجر     </th>
                                <th>اسم المنتج     </th>
                                
                                <th>سعر المنتج     </th>

                                <th>كمية المنتج  </th>
                                


                                <th>التاريخ  </th>



                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>@item.SalesInvoiceId</td>

                                   
                                   

                                    <td>
                                        @item.SupplierName
                                    </td>
                                    <td>
                                        @item.ProductName
                                    </td>

                                  
                                    <td>
                                        @item.ProductPrice

                                    <td>
                                            @item.ProductQty
                                    </td>
                                   


                                    <td>
                                            @item.CreatedDate
                                    </td>



                                </tr>

                            }


                        </tbody>
                      
                    </table>
                </div>
@section DataTableJS{

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script>
        $(function () {
            $("#MostSearchedProductsTable").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#MostSearchedProductsTable_wrapper .col-md-6:eq(0)');
            $('#example').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}
            
<!-- /.content -->

TawredatProject/Areas/Admin/Views/SalesInvoice/Index.cshtml
@model TawredatProject.Models.HomePageModel
<!-- Content Header (Page header) -->
@section DataTableStyles{

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}

<section class="content-header">
    <input type="hidden" id="Id" name="Id" />
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>عرض الفواتير  </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">الفواتير   </a></li>
                    <li class="breadcrumb-item active">عرض الفواتير   </li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
                <!-- /.card-header -->
                <div class="card-body">
                    <form asp-controller="SalesInvoice" asp-action="Index">
                        <div class="row">
                            <div class="col-xl-11">
                                <input type="text" placeholder="Search By Name" name="MyName" class="form-control" />
                            </div>
                            <div class="col-xl-1">
                                <input type="submit" value="Search" class="btn btn-primary" />
                            </div>
                        </div>
                    </form>


                    <br />

                    <table id="MosTable" class="table table-hover table-bordered table-striped text-center font-weight-bold">
                        <thead class="thead-dark">
                            <tr>
                                
                                <th> تاريخ الفاتورة </th>
                                <th>اسم المشتري </th>
                              
                               
                              
                                <th>اسم طريقة الدفع </th>
                                <th>اجمالي قيمة الفاتورة </th>
                                <th>مكان  التسليم     </th>
                               
                              
                              
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lstSalesInvoices)
                            {

                                <tr>
                                    <td>
                                        @item.CreatedDate
                                    </td>

                                    <td>
                                        @item.SupplierName
                                    </td>

                                    <td>
                                        @item.PaymnetMethodName
                                    </td>
                                    <td>
                                        @item.TotalInvoiceAfter
                                    </td>
                                    <td>
                                        @item.DeliveryAddress
                                    </td>

                                    <td>
@*                                        <a asp-controller="Landing" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-light x-Landing  px-8">Update</a>
*@
                                <a asp-controller="SalesInvoice" asp-action="Details" asp-route-id="@item.SalesInvoiceId" class="btn btn-light x-Landing  px-8">Details</a>
                                    </td>
                                   
                                </tr>

                            }


                        </tbody>
                     
                    </table>
                </div>
                <!-- /.card-body -->
           
    @section DataTableJS{

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <script src="~/plugins/jquery/jquery.min.js"></script>


    <script>
        $(function () {
            $("#MosTable").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#MosTable_wrapper .col-md-6:eq(0)');
            $('#example').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });


        <!-- ...your existing code... -->


            $(function () {

                $(".x-Landing").click(function () {

                    var landingId = $(this).val(); 
                    $.ajax({

                        type: "GET",
                        url: "/SalesInvoice/Details/" + landingId,
                        data: { SalesInvoiceId: landingId },
                        success: function (res) {



                           
                        }
                    });

                });




            });
   

    </script>
}