TawredatProject/Areas/Admin/Controllers/SettingController.cs
using TawredatProject.Models;
using BL;
using Domains;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
using Microsoft.AspNetCore.Authorization;

namespace TawredatProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SettingController : Controller
    {
        SettingService settingService;
        TawredatDbContext ctx;
        public SettingController(SettingService SettingService , TawredatDbContext context)
        {
            settingService = SettingService;
            ctx = context;

        }
        [Authorize(Roles = "Admin,الاعدادات")]
        public IActionResult Index()
        {

            HomePageModel model = new HomePageModel();
            model.lstSettings = settingService.getAll();

            return View(model);


        }




        [HttpPost]
        public async Task<IActionResult> Save(TbSetting ITEM, int id, List<IFormFile> files)
        {
            if (ITEM.SettingId == null)
            {


                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.MainConsultingImage = ImageName;
                    //    }
                    //}





                    var result = settingService.Add(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "Setting Profile successfully Created.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in Setting Profile  Creating.";
                    }


                }


            }
            else
            {
                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.MainConsultingImage = ImageName;
                    //    }
                    //}






                    var result = settingService.Edit(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "Setting Profile successfully Updated.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in Setting Profile  Updating.";
                    }

                }
            }




            HomePageModel model = new HomePageModel();
            model.lstSettings = settingService.getAll();
            return View("Index", model);
        }




        [Authorize(Roles = "Admin,حذف الاعدادات")]
        public IActionResult Delete(Guid id)
        {

            TbSetting oldItem = ctx.TbSettings.Where(a => a.SettingId == id).FirstOrDefault();



            var result = settingService.Delete(oldItem);
            if (result == true)
            {
                TempData[SD.Success] = "Setting Profile successfully Removed.";
            }
            else
            {
                TempData[SD.Error] = "Error in Setting Profile  Removing.";
            }

            HomePageModel model = new HomePageModel();
            model.lstSettings = settingService.getAll();
            return View("Index", model);



        }



        [Authorize(Roles = "Admin,اضافة او تعديل الاعدادات")]
        public IActionResult Form(Guid? id)
        {
            TbSetting oldItem = ctx.TbSettings.Where(a => a.SettingId == id).FirstOrDefault();
            oldItem = ctx.TbSettings.Where(a => a.SettingId == id).FirstOrDefault();

            return View(oldItem);
        }
    }
}

TawredatProject/Areas/Admin/Views/Setting/Index.cshtml
@model TawredatProject.Models.HomePageModel
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>عرض    الاعدادات</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">   الاعدادات</a></li>
                    <li class="breadcrumb-item active">عرض    الاعدادات</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">


            <div class="card">
                <div class="card-header">
                   
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped ">
                        <thead>
                            <tr>
                                <th>    ضريبة القيمة المضافة</th>
                             
                                <th>تعديل</th>
                               
                                <th>حذف</th>
                              
                               
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lstSettings)
                            {

                                <tr>
                                    <td>@item.ValueAddedTax</td>
                                   

                                   @* <td style="width:10%">
                                       
                                            <img style="max-width: 100%; " max-height: 100%;" src="@string.Format("/Uploads/{0}",item.AboutAppForWhom)" alt="Img placeholder">

                                           
                                          
                                       
                                       
                                    </td>*@
                                    <td>
                                        <a asp-area="Admin" asp-controller="Setting" asp-action="Form" asp-route-id="@item.SettingId" class="btn btn-info text-white" style="cursor:pointer">
                                            تعديل
                                        </a>
                                    </td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="Setting" asp-action="Delete" asp-route-id="@item.SettingId" class="btn btn-danger text-white" style="cursor:pointer">
                                            حذف
                                        </a>
                                    </td>
                                  
                                   
                                </tr>

                            }


                        </tbody>
                        <tfoot>
                            <tr>
                                <th>    ضريبة القيمة المضافة</th>

                                <th>تعديل</th>

                                <th>حذف</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->