TawredatProject/Areas/Admin/Controllers/UsersActivitiesController.cs
using BL;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using TawredatProject.Models;

namespace TawredatProject.Areas.Admin.Controllers
{


    [Area("Admin")]
    public class UsersActivitiesController : Controller
    {
        TawredatDbContext ctx;
        UserManager<ApplicationUser> Usermanager;
        public UsersActivitiesController(UserManager<ApplicationUser> usermanager, TawredatDbContext context)
        {

            Usermanager = usermanager;
            ctx = context;

        }
        public IActionResult Index()
        {
            HomePageModel model = new HomePageModel();
            model.UserData = Usermanager.Users.ToList();

            return View(model);
        }
        public IActionResult PurchasingManagerList()
        {
            HomePageModel model = new HomePageModel();
            model.UserData = Usermanager.Users.Where(a=>a.Status== "مدير مشتريات").ToList();

            return View(model);
        }
        public IActionResult SupplierList()
        {
            HomePageModel model = new HomePageModel();
            model.UserData = Usermanager.Users.Where(a => a.Status == "تاجر").ToList();

            return View(model);
        }
        public IActionResult DoctorList()
        {
            HomePageModel model = new HomePageModel();
            model.UserData = Usermanager.Users.Where(a => a.Status == "طبيب").ToList();

            return View(model);
        }
        public IActionResult UserList()
        {
            HomePageModel model = new HomePageModel();
            model.UserData = Usermanager.Users.Where(a => a.Status ==null).ToList();

            return View(model);
        }
    }
}

TawredatProject/Areas/Admin/Views/UsersActivities/DoctorList.cshtml
@model TawredatProject.Models.HomePageModel
@{
    ViewData["Title"] = "Users";
}

@section DataTableStyles{

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>تقرير الاطباء</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#"></a></li>
                    <li class="breadcrumb-item active">تقرير الاطباء</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- /.card-header -->
<div class="card-body">
    <form asp-controller="UsersActivities" asp-action="DoctorList">
        <div class="row">
            <div class="col-xl-11">
                <input type="text" placeholder="Search By Name" name="MyName" class="form-control" />
            </div>
            <div class="col-xl-1">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </form>


    <br />

    <table id="UsersActivitiesTable" class="table table-hover table-bordered table-striped text-center font-weight-bold">

        <thead>
            <tr>

                <th> اسم المستخدم </th>
                @* <th>اسم المدينة </th>*@



                <th>البريد الالكترونى     </th>
                <th>رقم الهاتف       </th>
                <th>تاريخ الانشاء     </th>
               @* <th>تابع لمدير مشتريات    </th>*@




            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UserData)
            {

                <tr>
                    <td>
                        @item.FirstName
                    </td>

                    @*  <td>
                @item.CityName
                </td>*@





                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.PhoneNumber
                    </td>
                     <td>
                @item.CreatedDate
                </td>



                </tr>

            }


        </tbody>

    </table>

</div>
<!-- /.card-body -->
@section DataTableJS{

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script>
        $(function () {
            $("#UsersActivitiesTable").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#UsersActivitiesTable_wrapper .col-md-6:eq(0)');
            $('#example').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}

TawredatProject/Areas/Admin/Views/UsersActivities/Index.cshtml
@model TawredatProject.Models.HomePageModel
@{
    ViewData["Title"] = "Users";
}

@section DataTableStyles{

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>تقرير المستخدمين</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">ادارة التقارير</a></li>
                    <li class="breadcrumb-item active">تقرير المستخدمين</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- /.card-header -->
<div class="card-body">
    <form asp-controller="UsersActivities" asp-action="Index">
        <div class="row">
            <div class="col-xl-11">
                <input type="text" placeholder="Search By Name" name="MyName" class="form-control" />
            </div>
            <div class="col-xl-1">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </form>


    <br />

    <table id="UsersActivitiesTable" class="table table-hover table-bordered table-striped text-center font-weight-bold">

        <thead>
            <tr>

                <th> اسم المستخدم </th>
               @* <th>اسم المدينة </th>*@



                <th>البريد الالكترونى     </th>
                <th>رقم الهاتف       </th>
                <th>تاريخ الانشاء     </th>




            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UserData)
            {

                <tr>
                    <td>
                        @item.FirstName
                    </td>

                  @*  <td>
                        @item.CityName
                    </td>*@





                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.PhoneNumber
                    </td>
                   <td>
                        @item.CreatedDate
                    </td>



                </tr>

            }


        </tbody>

    </table>

</div>
<!-- /.card-body -->
@section DataTableJS{

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script>
        $(function () {
            $("#UsersActivitiesTable").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#UsersActivitiesTable_wrapper .col-md-6:eq(0)');
            $('#example').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}

TawredatProject/Areas/Admin/Views/UsersActivities/PurchasingManagerList.cshtml
@model TawredatProject.Models.HomePageModel
@{
    ViewData["Title"] = "Users";
}

@section DataTableStyles{

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>تقريرمديرى المشتريات</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#"></a></li>
                    <li class="breadcrumb-item active">تقرير مديرى المشتريات</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- /.card-header -->
<div class="card-body">
    <form asp-controller="UsersActivities" asp-action="PurchasingManagerList">
        <div class="row">
            <div class="col-xl-11">
                <input type="text" placeholder="Search By Name" name="MyName" class="form-control" />
            </div>
            <div class="col-xl-1">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </form>


    <br />

    <table id="UsersActivitiesTable" class="table table-hover table-bordered table-striped text-center font-weight-bold">

        <thead>
            <tr>

                <th> اسم المستخدم </th>
                @* <th>اسم المدينة </th>*@



                <th>البريد الالكترونى     </th>
                <th>رقم الهاتف       </th>
                <th>تاريخ الانشاء     </th>




            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UserData)
            {

                <tr>
                    <td>
                        @item.FirstName
                    </td>

                    @*  <td>
                @item.CityName
                </td>*@





                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.PhoneNumber
                    </td>
                     <td>
                @item.CreatedDate
                </td>



                </tr>

            }


        </tbody>

    </table>

</div>
<!-- /.card-body -->
@section DataTableJS{

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script>
        $(function () {
            $("#UsersActivitiesTable").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#UsersActivitiesTable_wrapper .col-md-6:eq(0)');
            $('#example').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}

TawredatProject/Areas/Admin/Views/UsersActivities/SupplierList.cshtml
@model TawredatProject.Models.HomePageModel
@{
    ViewData["Title"] = "Users";
}

@section DataTableStyles{

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>تقرير التجار</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#"></a></li>
                    <li class="breadcrumb-item active">تقرير التجار</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- /.card-header -->
<div class="card-body">
    <form asp-controller="UsersActivities" asp-action="SupplierList">
        <div class="row">
            <div class="col-xl-11">
                <input type="text" placeholder="Search By Name" name="MyName" class="form-control" />
            </div>
            <div class="col-xl-1">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </form>


    <br />

    <table id="UsersActivitiesTable" class="table table-hover table-bordered table-striped text-center font-weight-bold">

        <thead>
            <tr>

                <th> اسم المستخدم </th>
                @* <th>اسم المدينة </th>*@



                <th>البريد الالكترونى     </th>
                <th>رقم الهاتف       </th>
                <th>تاريخ الانشاء     </th>




            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UserData)
            {

                <tr>
                    <td>
                        @item.FirstName
                    </td>

                    @*  <td>
                @item.CityName
                </td>*@





                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.PhoneNumber
                    </td>
                      <td>
                @item.CreatedDate
                </td>



                </tr>

            }


        </tbody>

    </table>

</div>
<!-- /.card-body -->
@section DataTableJS{

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script>
        $(function () {
            $("#UsersActivitiesTable").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#UsersActivitiesTable_wrapper .col-md-6:eq(0)');
            $('#example').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}

TawredatProject/Areas/Admin/Views/UsersActivities/UserList.cshtml
@model TawredatProject.Models.HomePageModel
@{
    ViewData["Title"] = "Users";
}

@section DataTableStyles{

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>تقرير المستخدمين</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#"></a></li>
                    <li class="breadcrumb-item active">تقرير المستخدمين</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>


<!-- /.card-header -->
<div class="card-body">
    <form asp-controller="UsersActivities" asp-action="UserList">
        <div class="row">
            <div class="col-xl-11">
                <input type="text" placeholder="Search By Name" name="MyName" class="form-control" />
            </div>
            <div class="col-xl-1">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </form>


    <br />

    <table id="UsersActivitiesTable" class="table table-hover table-bordered table-striped text-center font-weight-bold">

        <thead>
            <tr>

                <th> اسم المستخدم </th>
                @* <th>اسم المدينة </th>*@



                <th>البريد الالكترونى     </th>
                <th>رقم الهاتف       </th>
                @*<th>المكان     </th>*@




            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UserData)
            {

                <tr>
                    <td>
                        @item.UserName
                    </td>

                    @*  <td>
                @item.CityName
                </td>*@





                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.PhoneNumber
                    </td>
                    @*  <td>
                @item.Location
                </td>*@



                </tr>

            }


        </tbody>

    </table>

</div>
<!-- /.card-body -->
@section DataTableJS{

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <script>
        $(function () {
            $("#UsersActivitiesTable").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#UsersActivitiesTable_wrapper .col-md-6:eq(0)');
            $('#example').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
}