TawredatProject/Areas/Admin/Controllers/PurchaseSubscribtionController.cs
using BL;
using Domains;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using System;
using TawredatProject.Models;
using Microsoft.AspNetCore.Authorization;

namespace TawredatProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PurchaseSubscribtionController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        PurchaserSubscriptionService purchaserSubscription;

        TawredatDbContext ctx;
        public PurchaseSubscribtionController(UserManager<ApplicationUser> userManager, PurchaserSubscriptionService PurchaserSubscription, TawredatDbContext context)
        {
           
            _userManager = userManager;
            purchaserSubscription = PurchaserSubscription;
            ctx = context;

        }
        [Authorize(Roles = "Admin, اشتراكات مديري المشتريات")]
        public IActionResult Index()
        {

            HomePageModel model = new HomePageModel();
            model.lstPurchaseSubscribtion = purchaserSubscription.getAll();

            return View(model);


        }




        [HttpPost]
        public async Task<IActionResult> Save(TbPurchaseSubscribtion ITEM, int id, List<IFormFile> files)
        {
            ITEM.PurchaserName = _userManager.Users.Where(a => a.Id == ITEM.PurchaserId.ToString()).FirstOrDefault().FirstName;
            if (ITEM.PurchaserSubscriptionId == null)
            {


                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.ab = ImageName;
                    //    }
                    //}





                    var result = purchaserSubscription.Add(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "Purchaser Subscription  Profile successfully Created.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in Purchaser Subscription Profile  Creating.";
                    }


                }


            }
            else
            {
                if (ModelState.IsValid)
                {
                    //foreach (var file in files)
                    //{
                    //    if (file.Length > 0)
                    //    {
                    //        string ImageName = Guid.NewGuid().ToString() + ".jpg";
                    //        var filePaths = Path.Combine(Directory.GetCurrentDirectory(), @"wwwroot\Uploads", ImageName);
                    //        using (var stream = System.IO.File.Create(filePaths))
                    //        {
                    //            await file.CopyToAsync(stream);
                    //        }
                    //        ITEM.MainConsultingImage = ImageName;
                    //    }
                    //}






                    var result = purchaserSubscription.Edit(ITEM);
                    if (result == true)
                    {
                        TempData[SD.Success] = "Purchaser Subscription Profile successfully Updated.";
                    }
                    else
                    {
                        TempData[SD.Error] = "Error in Purchaser Subscription Profile  Updating.";
                    }

                }
            }




            HomePageModel model = new HomePageModel();
            model.lstPurchaseSubscribtion = purchaserSubscription.getAll();
            return View("Index", model);
        }




        [Authorize(Roles = "Admin,حذف   اشتراكات مديري المشتريات")]
        public IActionResult Delete(Guid id)
        {

            TbPurchaseSubscribtion oldItem = ctx.TbPurchaseSubscribtions.Where(a => a.PurchaserSubscriptionId == id).FirstOrDefault();



            var result = purchaserSubscription.Delete(oldItem);
            if (result == true)
            {
                TempData[SD.Success] = "Purchaser Subscription Profile successfully Removed.";
            }
            else
            {
                TempData[SD.Error] = "Error in Purchaser Subscription Profile  Removing.";
            }

            HomePageModel model = new HomePageModel();
            model.lstPurchaseSubscribtion = purchaserSubscription.getAll();
            return View("Index", model);



        }



        [Authorize(Roles = "Admin, اضافة او تعديل   اشتراكات مديري المشتريات")]
        public IActionResult Form(Guid? id)
        {
            TbPurchaseSubscribtion oldItem = ctx.TbPurchaseSubscribtions.Where(a => a.PurchaserSubscriptionId == id).FirstOrDefault();
            ViewBag.Purchasers = _userManager.Users.Where(a => a.Status == "مدير مشتريات").ToList();

            return View(oldItem);
        }
    }
}

TawredatProject/Areas/Admin/Views/PurchaseSubscribtion/Form.cshtml
@model Domains.TbPurchaseSubscribtion
<!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
                <h1> اشتراكات مديري المشتريات </h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">اشتراكات مديري المشتريات </a></li>
                    <li class="breadcrumb-item active">اضافة اشتراكات مديري المشتريات </li>
            </ol>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <!-- left column -->
          <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
               
              </div>
              <!-- /.card-header -->
              <!-- form start -->
                    <form id="form" enctype="multipart/form-data" method="post" role="form" asp-area="Admin" asp-controller="PurchaseSubscribtion" asp-action="Save">
                <div class="card-body">
                            <div asp-validation-summary="All" class="text-danger"></div>


                            <section class="content">
                                <div class="container-fluid">
                                    <!-- SELECT2 EXAMPLE -->
                                    <div class="card card-default">
                                        <div class="card-header">
                                            <h3 class="card-title">اسم مدير المشتريات</h3>


                                        </div>
                                        <!-- /.card-header -->
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label>اسم مدير المشتريات</label>
                                                        <select asp-for="PurchaserId" asp-items="@(new SelectList(ViewBag.Purchasers , "Id" , "FirstName"))" class="form-control select2" style="width: 100%;" required>
                                                            <option value="">اختر</option>


                                                        </select>
                                                        <span asp-validation-for="PurchaserId" class="text-danger"></span>
                                                    </div>

                                                </div>

                                            </div>
                                            <!-- /.row -->
                                        </div>
                                        <!-- /.card-body -->

                                    </div>
                                    <!-- /.card -->

                                </div>
                            </section>
                  <div class="form-group">
                                <input type="hidden"  asp-for="PurchaserSubscriptionId" >
                                <input type="hidden" asp-for="CreatedDate">
                                <input type="hidden" asp-for="PurchaserName">
                                <label for="exampleInputEmail1">اسم  الباكاج</label>
                                <input type="text" class="form-control" id="exampleInputEmail1" asp-for="SubscriptionPackage" placeholder="اسم الباكاج ">
                                <span asp-validation-for="SubscriptionPackage" class="text-danger"></span>
                  </div>
                 
                

                            <div class="form-group">
                                <label for="exampleInputPassword1"> بداية الاشتراك</label>
                                <input type="datetime-local" class="form-control" id="exampleInputPassword1" asp-for="StartdDate" placeholder=" بداية الاشتراك">
                                <span asp-validation-for="StartdDate" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputPassword1"> نهاية الاشتراك</label>
                                <input type="datetime-local" class="form-control" id="exampleInputPassword1" asp-for="EnddDate" placeholder=" نهاية الاشتراك">
                                <span asp-validation-for="EnddDate" class="text-danger"></span>
                            </div>

                         
                          


                       
                 
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
            <!-- /.card -->

          
            <!-- /.card -->

          </div>
          <!--/.col (left) -->
      
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
<script type="application/javascript">
    var a = document.getElementById("inputGroupFile02");
    a.value= "ahmed.txt";
</script>
@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
     
    }
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script>
        //alert("ahmed");
        const logo = document.getElementById('selectedFile');
        const license = document.getElementById('selectedFiles');
        const form = document.getElementById('form')
        const erroElement = document.getElementById('error')
        const erroElement1 = document.getElementById('error1')
        form.addEventListener('submit',(e)=> 
        {
            //e.preventDefault();
            let messages =[];
            let messages2 = [];
            if (logo.value === '' || logo.value == null) 
            {
                //alert('ahmed');
                messages.push('This field is required');
                erroElement.innerHTML = messages;
            }
            else 
            {
                messages =[];
                erroElement.innerHTML = messages;

            }
            if (license.value === '' || license.value == null) {
                //alert('ahmed');
                messages2.push('This field is required');
                erroElement1.innerHTML = messages2;
            }
            else {
                messages = [];
                erroElement1.innerHTML = messages2;

            }


        });
    </script>
    }

TawredatProject/Areas/Admin/Views/PurchaseSubscribtion/Index.cshtml
@model TawredatProject.Models.HomePageModel
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>عرض اشتراكات مديري المشتريات </h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">اشتراكات مديري المشتريات </a></li>
                    <li class="breadcrumb-item active">عرض اشتراكات مديري المشتريات </li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">


            <div class="card">
                <div class="card-header">
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <table id="example1" class="table table-bordered table-striped ">
                        <thead>
                            <tr>
                                <th>اسم مديري المشتريات </th>
                                <th>اسم الباكاج </th>


                                <th>بداية الاشتراك </th>
                                <th>نهاية الاشتراك </th>
                                <th>تعديل</th>

                                <th>حذف</th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lstPurchaseSubscribtion)
                            {

                                <tr>
                                    <td>@item.PurchaserName</td>
                                    <td>
                                        @item.SubscriptionPackage
                                    </td>



                                    <td>
                                        @item.StartdDate
                                    </td>
                                    <td>
                                        @item.EnddDate
                                    </td>

                                    <td>
                                        <a asp-area="Admin" asp-controller="PurchaseSubscribtion" asp-action="Form" asp-route-id="@item.PurchaserSubscriptionId" class="btn btn-info text-white" style="cursor:pointer">
                                            تعديل
                                        </a>
                                    </td>
                                    <td>
                                        <a asp-area="Admin" asp-controller="PurchaseSubscribtion" asp-action="Delete" asp-route-id="@item.PurchaserSubscriptionId" class="btn btn-danger text-white" style="cursor:pointer">
                                            حذف
                                        </a>
                                    </td>


                                </tr>

                            }


                        </tbody>
                        <tfoot>
                            <tr>
                                <th>اسم مديري المشتريات </th>
                                <th>اسم الباكاج </th>


                                <th>بداية الاشتراك </th>
                                <th>نهاية الاشتراك </th>
                                <th>تعديل</th>

                                <th>حذف</th>

                            </tr>
                        </tfoot>
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>
<!-- /.content -->